import {
  AlertTriangle,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  Briefcase,
  Building2,
  CalendarClock,
  Calculator,
  CircleHelp,
  Clock,
  Cloud,
  Code2,
  CreditCard,
  Database,
  DraftingCompass,
  Factory,
  FileText,
  Filter,
  Fingerprint,
  Globe,
  GraduationCap,
  Headphones,
  Inbox,
  LifeBuoy,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Package,
  Palette,
  Phone,
  PieChart,
  Repeat,
  Shield,
  Headset,
  HeartHandshake,
  IndianRupee,
  Layers,
  Megaphone,
  MessageCircle,
  Network,
  PenTool,
  Plug,
  Puzzle,
  ReceiptText,
  Rocket,
  ScanLine,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Store,
  Target,
  TrendingUp,
  Truck,
  Tv,
  UserCheck,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Central icon registry. Data files reference icons by string name
 * (`IconName`), which keeps the data layer serializable; components
 * resolve them to Lucide components with `getIcon()`.
 */
export const ICONS = {
  "alert-triangle": AlertTriangle,
  award: Award,
  "bar-chart": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building2,
  "calendar-clock": CalendarClock,
  calculator: Calculator,
  "circle-help": CircleHelp,
  clock: Clock,
  cloud: Cloud,
  code: Code2,
  "credit-card": CreditCard,
  database: Database,
  "drafting-compass": DraftingCompass,
  factory: Factory,
  "file-text": FileText,
  filter: Filter,
  fingerprint: Fingerprint,
  globe: Globe,
  "graduation-cap": GraduationCap,
  headphones: Headphones,
  inbox: Inbox,
  "life-buoy": LifeBuoy,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  package: Package,
  palette: Palette,
  phone: Phone,
  "pie-chart": PieChart,
  repeat: Repeat,
  shield: Shield,
  headset: Headset,
  "heart-handshake": HeartHandshake,
  "indian-rupee": IndianRupee,
  layers: Layers,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  network: Network,
  "pen-tool": PenTool,
  plug: Plug,
  puzzle: Puzzle,
  "receipt-text": ReceiptText,
  rocket: Rocket,
  "scan-line": ScanLine,
  search: Search,
  send: Send,
  settings: Settings,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  store: Store,
  target: Target,
  "trending-up": TrendingUp,
  truck: Truck,
  tv: Tv,
  "user-check": UserCheck,
  users: Users,
  wallet: Wallet,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

/** Every icon name available to the data layer. */
export type IconName = keyof typeof ICONS;

/** Resolve an icon name from the data layer to its Lucide component. */
export function getIcon(name: IconName): LucideIcon {
  return ICONS[name];
}
